config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :users
  resources :passwords, param: :token do
    resources :bids, only: [ :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  resources :bids
  # Defines the root path route ("/")
  root "bids#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bid.rb
class Bid < ApplicationRecord
  validates :loc, presence: true
  validates :item, presence: true
  validates :price, presence: true
  validates :phnumber, presence: true
  validates :bid_or_offer, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  allow_unauthenticated_access only: %i[index show]
  before_action :set_bid, only: %i[ show destroy ]
  def index
    @bids = Bid.all
  end

  def show
    @bid = Bid.find(params[:id])
  end

  def new
    @bid = Bid.new
  end

  def create
    @bid = Bid.new(bid_params.merge(user_id: get_user_id))
    if @bid.save
      redirect_to bids_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bid.destroy
    redirect_to bids_path
  end

  private
    def set_bid
      @bid = Bid.find(params[:id])
    end
    def bid_params
      params.expect(bid: [ :loc, :item, :price, :phnumber, :bid_or_offer, :user_id ])
    end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?, :get_user_id
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def get_user_id
      Current.session.user_id
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to root_path
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[new create]

  def show
  end

  def index
  end

  def new
    @user = User.new
  end

  def create
    begin
      @user = User.new(user_params)
      if @user.save
        redirect_to new_session_path
      else
        redirect_to new_user_path, alert: "Email already in use"
      end
    rescue ActiveRecord::RecordNotUnique
      redirect_to new_user_path, alert: "Email already in use"
    end
  end

  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:email_address, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/index.html.erb
<h1 class= "text-3xl font-bold p-2 text-center">northwestern meal bazaar</h1>
<div class= "p-2">
  <p>Welcome to the Northwestern Meal Bazaar! This is an online marketplace for buying and selling 
  meal exchanges and dining hall swipes- you can think of it as Facebook marketplace for NU meals. If you'd like to sell a dining hall swipe/meal exchange, simply 
  enter create an Offer item and input the necessary info. If you'd like to buy a dining hall swipe/meal exchange, 
  create a Bid item to put out a request for an item at your desired price. Once your bid or offer has been fulfilled, 
  you can delete your item. 
  </p>
</div>
<div class="text-base p-2 text-center">
  <div class= "bg-indigo-100 max-w-52 rounded-lg hover:bg-green-100"><%= link_to "create new bid or offer", new_bid_path %></div>
</div>
<div class= "grid grid-cols-2 bg-gray-100 border border-black-100 gap-4 p-2">
  <div>
    <h2 class= "text-2xl font-bold">active bids</h2>
      <div class= "grid grid-cols-3 gap-4">
        <% @bids.order(:price).each do |bid| %>
        <% if bid.bid_or_offer.eql? "Bid" %>
          <div class= "grid grid-cols-1 max-w-md bg-indigo-100/50 rounded-lg border border-indigo-200 p-2"> 
            <div> <%= bid.item %> </div>
            <div> <%= bid.loc %> </div>
            <div> $<%= bid.price %> </div>
            <div> <%= bid.phnumber %> </div>
              <% if authenticated? %>
                  <% if get_user_id == bid.user_id %>
                     <div class= "text-center rounded-lg bg-indigo-200/50 hover:bg-red-200/100">
                        <%= button_to "Delete Item", bid, method: :delete %>
                      </div>
                  <% end %>
              <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div>
    <h2 class= "text-2xl font-bold"> active offers </h2>
    <div class= "grid grid-cols-3 gap-4">
      <% @bids.order(:price).each do |bid| %>
        <% if bid.bid_or_offer.eql? "Offer"%>
          <div class= "grid grid-cols-1 bg-indigo-100/50 border border-indigo-200 rounded-lg p-2"> 
            <div><%= bid.item %></div>
            <div><%= bid.loc %></div>
            <div>$<%= bid.price %></div>
            <div><%= bid.phnumber %></div>
            <% if authenticated? %>
              <% if get_user_id == bid.user_id %>
                     <div class= "text-center bg-indigo-200/50 rounded-lg hover:bg-red-200/100">
                       <%= button_to "Delete Item", bid, method: :delete %>
                      </div>
                  <% end %>
              <% end %>

          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/bids/new.html.erb
<h1 class= "p-5 text-3xl font-bold"> New Item: </h1>
<%= form_with model: @bid do |form| %>
  <div class= "transform translate-x-20 p-10 grid grid-cols-1 gap-4 bg-gradient-to-r from-indigo-100 to-blue-100 max-w-xl rounded-xl">
    <div class= "grid grid-cols-1 max-w-md">
      <%= form.label "Location" %>
      <%= form.text_field :loc %>
    </div>
    <div class= "grid grid-cols-1 max-w-md">
      <%= form.label "Item" %>
      <%= form.text_field :item %>
    </div>
    <div class= "grid grid-cols-1 max-w-md">
      <%= form.label "Price" %>
      <%= form.text_field :price%>
    </div>
    <div class= "grid grid-cols-1 max-w-md">
      <%= form.label "Phone Number" %>
      <%= form.text_field :phnumber %>
    </div>
    <div class= "grid grid-cols-2 max-w-sm justify-self-start">
      <%= form.radio_button :bid_or_offer, "Bid"%>
      <%= form.label :bid_or_offer_bid, "Bid"%>
      <%= form.radio_button :bid_or_offer, "Offer"%>
      <%= form.label :bid_or_offer_bid, "Offer"%>
    </div>
    <div class= "bg-indigo-300 w-28 rounded-xl text-center hover:bg-green-300">
      <%= form.submit "Create Item" %>
    </div>
  </div>

<% end %>

app/views/bids/show.html.erb
<% if @bid.bid_or_offer == true%>
  <h1>Bid for <%= @bid.item%> at <%= @bid.loc%> </h1>
<%else%>
  <h1> Offer for <%= @bid.item%> at <%= @bid.loc%> </h1>
<%end%>
<div>
  <% if authenticated? %>
      <% if get_user_id == @bid.user_id %>
        <%= button_to "Delete item", @bid, method: :delete %>
      <% end %>
  <% end %>
</div>
<%= link_to "Back", bids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Northwestern Meal Bazaar" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/fez.png" type="image/png">
    <link rel= "icon" href="/fez.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class= "font-serif">
    <nav class= "p-1 font-bold grid grid-cols-3 bg-gradient-to-r from-indigo-200 to-blue-200">
      <%= link_to "home", root_path %></div>
      <%= button_to "log out", session_path, method: :delete if authenticated? %>
      <%= link_to "log in", new_session_path unless authenticated?%></div>
    <%= link_to "sign up", new_user_path unless authenticated? %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= tag.div(flash[:notice], style: "color:green") if flash[:notice] %>
<h1 class= "text-3xl font-bold p-4"> Create Account </h1>
<div class= "transform translate-x-20 p-2">
  <%= form_with model: @user do |form| %>
    <div class= "grid p-2 max-cols-1 max-w-52">
        <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", 
            placeholder: "Enter your email address", value: params[:email_address]
        %> <br>
        <%= form.password_field :password, required: true, placeholder: "Enter your password", maxlength: 72 %><br> 
      <div class= "transform bg-indigo-200 text-center max-w-32 text-md rounded-lg">
        <%= form.submit "Create Account" %>
      </div>
    </div>
</div>
<% end %>